
[tool.poetry]
name = "blynclight"
version = "0.4.8"
description = "Python language bindings for Embrava BlyncLight devices."
authors = ["Erik O'Shaughnessy <erik.oshaughnessy@gmail.com>"]
license = "Apache-2.0"
readme = "README.rst"
repository = "https://github.com/JnyJny/blynclight.git"
classifiers = [
    	    "Development Status :: 4 - Beta",
	    "Environment :: Console",
	    "Intended Audience :: Developers",
	    "License :: OSI Approved :: Apache Software License",
	    "Programming Language :: Python :: 3.6",
	    "Programming Language :: Python :: 3.7",
	    "Topic :: Artistic Software",
	    "Topic :: Multimedia :: Sound/Audio",
	    "Topic :: Utilities",
	    "Topic :: System :: Hardware",
]

[tool.poetry.scripts]

rainbow = "blynclight.scripts.rainbow:cli"
throbber = "blynclight.scripts.throbber:cli"
fli = "blynclight.scripts.fli:cli"
blync = "blynclight.scripts.blync:cli"

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.0"
requests = "^2.21"

[tool.poetry.dev-dependencies]
pytest = "^4.4"
pre-commit = "^1.15"
black = "^18.3-alpha.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
